### ISSUE TITLE
dinja.js fails with os error 2

### ISSUE THREAD

**Issue by imacki** [denjucks/dinja#3]
Hi
I thought I should report this issue in case you are not aware of it
I copied and pasted the curl command from the README.md to download dinja.js into an empty directory. It worked fine.
I ran the command "deno run -A dinja.js createproject"  and received an error message:
    **error: No such file or directory (os error 2)**
I tried running "deno -L debug run -A dinja.js createproject" but got a long output ending with:

fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/_globrex.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/_globrex.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/fmt/colors.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/fmt/colors.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/testing/diff.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/testing/diff.ts"
register_complete file:///home/ianma/www/Deno2020/dinja0/dinja.js
error: No such file or directory (os error 2)

I was unable to try out dinja because the command line script fails. I am running on deno 1.0.3 on Linux (Debian Testing). My copy of deno is the Linux binary downloaded by the "deno upgrade" command.

The full debug message was:

Deno isolate init with snapshots.
rust:shared_queue:reset
DEBUG JS - cwd /home/ianma/www/Deno2020/dinja0
DEBUG JS - args []
main_module file:///home/ianma/www/Deno2020/dinja0/dinja.js
fetch_source_file specifier: file:///home/ianma/www/Deno2020/dinja0/dinja.js 
⚠️️  Granted read access to "/home/ianma/www/Deno2020/dinja0/dinja.js"
byte pos BytePos(0) is on the line at byte pos BytePos(0)
char pos CharPos(0) is on the line at char pos CharPos(0)
byte is on line: 1
byte pos BytePos(71) is on the line at byte pos BytePos(71)
char pos CharPos(71) is on the line at char pos CharPos(71)
byte is on line: 2
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/mod.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/mod.ts"
byte pos BytePos(120) is on the line at byte pos BytePos(120)
char pos CharPos(120) is on the line at char pos CharPos(120)
byte is on line: 4
byte pos BytePos(158) is on the line at byte pos BytePos(158)
char pos CharPos(158) is on the line at char pos CharPos(158)
byte is on line: 5
byte pos BytePos(537) is on the line at byte pos BytePos(537)
char pos CharPos(537) is on the line at char pos CharPos(537)
byte is on line: 30
byte pos BytePos(566) is on the line at byte pos BytePos(566)
char pos CharPos(566) is on the line at char pos CharPos(566)
byte is on line: 31
byte pos BytePos(617) is on the line at byte pos BytePos(617)
char pos CharPos(617) is on the line at char pos CharPos(617)
byte is on line: 32
byte pos BytePos(649) is on the line at byte pos BytePos(649)
char pos CharPos(649) is on the line at char pos CharPos(649)
byte is on line: 33
fetch_source_file specifier: https://deno.land/x/dinja/lib/dexecutor/mod.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/dexecutor/mod.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/win32.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/win32.ts"
byte pos BytePos(140) is on the line at byte pos BytePos(140)
char pos CharPos(140) is on the line at char pos CharPos(140)
byte is on line: 5
byte pos BytePos(208) is on the line at byte pos BytePos(208)
char pos CharPos(208) is on the line at char pos CharPos(208)
byte is on line: 6
byte pos BytePos(315) is on the line at byte pos BytePos(315)
char pos CharPos(315) is on the line at char pos CharPos(315)
byte is on line: 13
byte pos BytePos(431) is on the line at byte pos BytePos(431)
char pos CharPos(431) is on the line at char pos CharPos(431)
byte is on line: 20
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/posix.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/posix.ts"
byte pos BytePos(135) is on the line at byte pos BytePos(135)
char pos CharPos(135) is on the line at char pos CharPos(135)
byte is on line: 5
byte pos BytePos(203) is on the line at byte pos BytePos(203)
char pos CharPos(203) is on the line at char pos CharPos(203)
byte is on line: 6
byte pos BytePos(268) is on the line at byte pos BytePos(268)
char pos CharPos(268) is on the line at char pos CharPos(268)
byte is on line: 8
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/common.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/common.ts"
byte pos BytePos(76) is on the line at byte pos BytePos(76)
char pos CharPos(76) is on the line at char pos CharPos(76)
byte is on line: 3
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/separator.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/separator.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/interface.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/interface.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/glob.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/glob.ts"
byte pos BytePos(0) is on the line at byte pos BytePos(0)
char pos CharPos(0) is on the line at char pos CharPos(0)
byte is on line: 1
byte pos BytePos(51) is on the line at byte pos BytePos(51)
char pos CharPos(51) is on the line at char pos CharPos(51)
byte is on line: 2
byte pos BytePos(92) is on the line at byte pos BytePos(92)
char pos CharPos(92) is on the line at char pos CharPos(92)
byte is on line: 3
byte pos BytePos(136) is on the line at byte pos BytePos(136)
char pos CharPos(136) is on the line at char pos CharPos(136)
byte is on line: 4
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/_constants.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/_constants.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/_util.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/_util.ts"
byte pos BytePos(113) is on the line at byte pos BytePos(113)
char pos CharPos(113) is on the line at char pos CharPos(113)
byte is on line: 4
byte pos BytePos(169) is on the line at byte pos BytePos(169)
char pos CharPos(169) is on the line at char pos CharPos(169)
byte is on line: 5
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/testing/asserts.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/testing/asserts.ts"
byte pos BytePos(75) is on the line at byte pos BytePos(75)
char pos CharPos(75) is on the line at char pos CharPos(75)
byte is on line: 2
byte pos BytePos(141) is on the line at byte pos BytePos(141)
char pos CharPos(141) is on the line at char pos CharPos(141)
byte is on line: 3
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/path/_globrex.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/path/_globrex.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/fmt/colors.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/fmt/colors.ts"
fetch_source_file specifier: https://deno.land/x/dinja/lib/std/testing/diff.ts 
⚠️️  Granted network access to "https://deno.land/x/dinja/lib/std/testing/diff.ts"
register_complete file:///home/ianma/www/Deno2020/dinja0/dinja.js
error: No such file or directory (os error 2)

**Comment by denjucks** [comment]
What deno version are you using? I received a similar error with newer versions of deno, and think it might just be an issue with the current deno version.

**Comment by imacki** [comment]
Hi

Output on commandline:

$ deno --version
deno 1.0.4
v8 8.4.300
typescript 3.9.2

Current error message with dinja (freshly downloaded):

*$* curl 
"https://raw.githubusercontent.com/denjucks/dinja/master/dinja.js" > 
dinja.js
   % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                  Dload  Upload   Total   Spent Left  Speed
100  131k  100  131k    0     0   360k      0 --:--:-- --:--:-- 
--:--:--  360k
*$* deno run -A dinja.js createproject
Compile file:///home/ianma/www/Deno2020/dinja/dinja.js
error: Uncaught AssertionError: Unexpected skip of the emit.
     at Object.assert ($deno$/util.ts:33:11)
     at compile ($deno$/compiler.ts:1170:7)
     at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
     at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
     at file:///home/ianma/www/Deno2020/dinja/__anonymous__:1:1
*$*

By the way, I enjoyed looking at the modular structure of dinja -- the 
applets with their own models, templates, etc.

Ian MacKinnell
97 Bundeena Drive
Bundeena NSW 2230
Australia

**Comment by denjucks** [comment]
Try downgrading to deno 1.0.2. There appears to be an issue with deno 1.0.4-1.0.5 on some machines that is causing this error

**Comment by denjucks** [comment]
Should be fixed now for Deno v1.1.0
